<div class="col-md-12">
	<div class="page-header">
		<h3>Administrador</h3>
	</div>
	<div class="col-md-6">
		<p>Data: <label> <?php echo date("d/m/Y") . " " . date("h:i:sa") ."<br />";?></label></p>
		<p>nome@exemplo.com.br</p>
		<p>CPF: 38956247525</p>
		<p>Matricula: 30205643</p>
		<br />
		<a type="button" class="btn btn-primary" href="index.php">Alterar dados pessoais</a>
		<br />
	</div>
	<div class="col-md-6">
		<img src="../imagens/adm.jpg" class="img-circle img-responsive" alt="Administrador" width="150">
	</div>

</div>