<!-- Início navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <img src="../imagens/icon_ru.png"/><label for="">RU - Refeitório Universitário UFBA</label>
    </div>
    
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="index.php.php">Home</a></li>
        <li><a href="administrador.php">Dados Pessoais</a></li>
        <li><a href="sobre.php">Sobre</a></li>
        <li><a href="faleconosco.php">Fale Conosco</a></li>
        <li><a href="#">Logoff</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<!-- Fim navbar -->